import smtplib
import os
from email.message import EmailMessage
from dotenv import load_dotenv

load_dotenv(dotenv_path="C:\Coding\Automated-CV-Scoring\main\doc.env") 
EMAIL_USER =os.getenv("EMAIL_USER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")




def send_email_with_attachment(to_email, candidate_name, pdf_path):
    msg = EmailMessage()
    msg['Subject'] = 'Your Resume Evaluation Report'
    msg['From'] = os.getenv("EMAIL_USER")
    msg['To'] = to_email

    msg.set_content(f"""
Hi {candidate_name},

Thank you for submitting your resume.

Attached is your automated evaluation report, generated by our AI screening tool. It provides an overview of how your resume aligns with key job-related skills and criteria.

We hope this feedback helps you in your preparation. Should your profile match any of our current or future openings, we will reach out to you for the next steps.

Wishing you all the best in your job search!

Best regards,
Talent Acquisition Team
""")

    # Attaching the PDF
    with open(pdf_path, 'rb') as f:
        file_data = f.read()
        file_name = os.path.basename(pdf_path)
    msg.add_attachment(file_data, maintype='application', subtype='pdf', filename=file_name)

    # Sending Email
    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
            smtp.login(EMAIL_USER, EMAIL_PASSWORD)
            smtp.send_message(msg)
        print(f"[✓] Email sent to {to_email}")
    except Exception as e:
        print(f"[!] Failed to send email: {e}")
